name: botpeas_action

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: adrielcodeco/docker-compose-run-action@v1
        with:
          compose-file: 'docker-compose.yml'
          compose-flags: '--env-file config/config.env up --build'
          service: ''
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
