name: botpeas_action

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: sdasd
        run: ls -lR; pwd
      - name: Start containers
        run: docker-compose --env-file ../config/config.env up --build
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
