name: botpeas_action

on:
  schedule:
    - cron: '0 */5 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create config
        run: |
          echo "" >> config/config.yml && echo -e "\ntelegram_token: \"$TELEGRAM_TOKEN\"" >> config/config.yml && echo "openai_api_key: \"$OPENAI_KEY\"" >> config/config.yml; cat config/config.yml
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
      - name: Start containers
        run: timeout 21300 docker-compose --env-file config/config.env up --build || true
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
